apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-slow
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-slow
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo Hello... && sleep 30
          restartPolicy: Never