apiVersion: batch/v1
kind: Job
metadata:
  name: hello-sleep
spec:
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - name: hello-sleep
        image: busybox:1.28
        command:
          - /bin/sh
          - -c
          - echo Sleeping... && sleep 31
      restartPolicy: Never