apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: busybox:1.28
        command:
          - /bin/sh
          - -c
          - echo Hello World!
      restartPolicy: Never