apiVersion: batch/v1
kind: Job
metadata:
  name: hello-error
spec:
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - name: hello-error
        image: busybox:1.28
        command: ["sh", "-c", "exit 1"]
      restartPolicy: Never
  backoffLimit: 0